In [1]:
import numpy as np

In [2]:
h1=np.array(5)

In [3]:
h1

array(5)

In [4]:
type(h1)

numpy.ndarray

In [5]:
range(5)

range(0, 5)

In [6]:
h2=np.array([1,2,3,4,5])

In [7]:
h2

array([1, 2, 3, 4, 5])

In [8]:
h3=np.array([[1,2,3,4,5],[1,3,5,7,9]])

In [9]:
h3

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 9]])

Array types

1.Zero Array

2.Ones Array

3.Empty Array

4.Array for range

In [10]:
zero_array=np.zeros(3)

In [11]:
zero_array

array([0., 0., 0.])

In [12]:
ones_array=np.ones(3)

In [13]:
ones_array

array([1., 1., 1.])

In [14]:
ones_array=np.ones((4,3))

In [15]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
h4=np.arange(3)

In [17]:
h4

array([0, 1, 2])

In [18]:
h5=np.arange(2,18)

In [19]:
h5

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [20]:
h6=np.transpose(h3)

In [21]:
h6

array([[1, 1],
       [2, 3],
       [3, 5],
       [4, 7],
       [5, 9]])

In [22]:
h7=np.ravel(h6)

In [23]:
h7

array([1, 1, 2, 3, 3, 5, 4, 7, 5, 9])

Concatenate

In [24]:
h1=np.array([2,3,5,6,7])
h2=np.array([1,2,3,4,5])

In [25]:
h1

array([2, 3, 5, 6, 7])

In [26]:
h2

array([1, 2, 3, 4, 5])

In [27]:
concat=np.concatenate([h1,h2])

In [33]:
concat

array([2, 3, 5, 6, 7, 1, 2, 3, 4, 5])

In [34]:
hori=np.vstack((h1,h2))

In [35]:
hori

array([[2, 3, 5, 6, 7],
       [1, 2, 3, 4, 5]])

In [36]:
hori=np.hstack((h1,h2))

In [37]:
hori

array([2, 3, 5, 6, 7, 1, 2, 3, 4, 5])